### ISSUE TITLE
HRM - Cho phép chỉnh họ tên nhân viên.

### ISSUE THREAD

**Issue by lqbinh1987** [dh-hos/dhg.hospitalhrm#3]
Theo yêu cầu của BV Thạnh Trị thì cho phép  chỉnh Họ và Tên của nhân viên trên module HRM.
Data: binh_thanhtri
![image](https://user-images.githubusercontent.com/99630883/169983601-f5ac46d8-e50d-412a-87d9-2adffe33abb6.png)

**Comment by ongtrieuhau** [comment]
Đây là yêu cầu từ xa xưa tới giờ, lý do hông cho hrm chỉnh là để gom 1 mối quản lý về quản trị hệ thống xử lý
