### ISSUE TITLE
Lỗi - Hiển thị sai tiền VTYT không tínhphí khi CLS không check Vật tư kèm theo

### ISSUE THREAD

**Issue by hvtuan1987** [dh-hos/dhg.hospitalhrm#5]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **Hà Văn Tuấn**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **19/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `95006`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Trung tâm Y tế huyện Phước Long**
-  ![ten_csdl](https://img.shields.io/badge/Tên%20cơ%20sở%20dữ%20liệu-:-blue?style=plastic&logo=github) `dbphuoclong_062023`
-  ![link_csdl](https://img.shields.io/badge/Tệp%20dữ%20liệu-:-blue?style=plastic&logo=github) [`Tải về tại đây`](link_csdl)

###### ![chi_tiet_loi](https://img.shields.io/badge/Chi%20tiết%20lỗi%20phát%20sinh-:-blue?style=for-the-badge&logo=github)

-  ![loi_benh_nhan](https://img.shields.io/badge/Chi%20tiết%20bệnh%20nhân-:-blue?style=plastic&logo=github)
   > _**MaBN**_: `2023010877` - _**MaKB**_: `2305012187` - _**MaBA**_: `2023004969` _**NgayKCB**_: `NgayKCB` - _**MaPhong**_: `MaPhong` - _**MaDV**_: `07` - _**ThangKT**_: `06` - _**NamKT**_: `2023`
-  ![loi_thuoc](https://img.shields.io/badge/Chi%20tiết%20thuốc-:-blue?style=plastic&logo=github)
   > _**KhoChan**_: `KhoChan` - _**KhoLe**_: `KhoLe` - _**MaHH**_: `MaHH` - _**SoHD**_: `SoHD` - _**NgayHD**_: `NgayHD` - _**ThangKT**_: `ThangKT` - _**NamKT**_: `NamKT`
-  ![loi_cls](https://img.shields.io/badge/Chi%20tiết%20CLS-:-blue?style=plastic&logo=github)
   > _**MaCLS**_: `MaCLS` - _**PhieuYC**_: `PhieuYC`
-  ![loi_bo_sung](https://img.shields.io/badge/Chi%20tiết%20bổ%20sung-:-blue?style=plastic&logo=github)
   > _**Khac**_: `Khac`

Chứng từ trên Treatment 01N.X23.0601.105107 có check Toa không tính phí thì Trên HRM phần Báo cáo-> Chi phí Thủ thuật - Phẫu thuật lại load lên thành tiền của Toa VT này nên sai với bệnh viên. Đúng thì ngay chổ cột VTYT không tính phítrên HRM chỉ  load lên khi nào  TT-PT  có check VTYT kèm theo . Hiện lại HRM đang load lên sai (và bệnh nhân có check nhiều toa Không tính phí trên Treatment thì HRM lại lấy tổng tiền của các chúng từ đó cộng lại nên sai luôn)
![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/97272364/af8923c0-ab10-4cf5-8c3c-3f896180e917)

Yêu cầu: TTPT nào có check Toa vật tư kèm theo không tinh phí mới load lên HRM chổ Báo cáo-> Bảng kê chi phí TT-PT (Cột VTYT không tính phí như hình dưới )

![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/97272364/6b76eab5-9a08-4195-8279-58c98cd707d0)

```

**Comment by ongtrieuhau** [comment]
Cái này thiết kế đã là như vậy (những chi phí thuộc toa không tính phí và cùng đơn vị thực hiện phẫu thuật sẽ lấy lên), những bệnh viện hiện tại đang lấy theo công thức này,  còn bệnh viện muốn yêu cầu khác thì cụ thể từng trường hợp, và có dữ liệu cụ thể nào lấy lên, dữ liệu nào hông lấy lên nhé.

**Comment by hvtuan1987** [comment]
Em mới thêm chứng từ : N25.V23.0622.112213 có cho thủ thuật có check Vật tư kèm theo á ( Cấu hình máy như hình dưới)
![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/97272364/9a0d72ef-7946-4ab8-90b5-ad3cc0d63dd7)

**Comment by ongtrieuhau** [comment]
Cập nhật HRM [3.23.0622.1](https://github.com/dh-hos/dhg.hospitalhrm/commit/a1cd9b27a8b8f23a5165f954416a8dfe39df11c0)

**Comment by hvtuan1987** [comment]
Bảng mới báo cáo hong load lên được dnah sách bệnh nhân có TTPT luôn á anh Hậu ơi !

![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/97272364/fec4bdbe-8e5d-4f82-91ea-83296c59b629)

**Comment by ongtrieuhau** [comment]
Hiện tại chỗ này đang theo cấu hình bảng lương nhé, nếu cấu hình khoa đó có toàn quyền của chấm công và lương của tất cả khoa thì mới load hết tất cả. Ngược lại chỉ lấy theo khoa cấu hình thôi.
