### ISSUE TITLE
Lỗi - Không cài đặt được module service khi máy có cài module HRM

### ISSUE THREAD

**Issue by le-an-87** [dh-hos/dhg.hospitalhrm#6]
<div align="center">

`Công ty TNHH Giải Pháp Kỹ Thuật Số DH - Mẫu: DH-08.1: Phiếu ghi nhận lỗi phát sinh DHG.Hospital 3.1`

</div>

<div align="center">
  <img src="https://raw.githubusercontent.com/dh-hos/dhg.hospitalprinter/main/Deploy_Tools/Logo.ico" alt="Simple Icons" width=70>
  <h1>PHIẾU GHI NHẬN LỖI PHÁT SINH</h1>  
</div>

#

-  ![nguoi_ghi_nhan](https://img.shields.io/badge/Người%20ghi%20nhận-:-blue?style=plastic&logo=github) **ÂN**
-  ![ngay_tiep_nhan](https://img.shields.io/badge/Ngày%20chi%20nhận-:-blue?style=plastic&logo=github) **29/06/2023**
-  ![mabvbh](https://img.shields.io/badge/Mã%20bệnh%20viện-:-blue?style=plastic&logo=github) `Tất cả`
-  ![khach_hang](https://img.shields.io/badge/Bệnh%20viện-:-blue?style=plastic&logo=github) **Tất cả**

###### ![mo_ta_loi](https://img.shields.io/badge/Mô%20tả%20thông%20tin%20lỗi-:-blue?style=for-the-badge&logo=github)

```
Module HRM bản cài đặt HRM.v3.23.0622.1 khi cài đặt thì hiển thị tên phiên phải là DHG.Hospitall service.

Khi cài module HRM rồi cài tiếp module service thì báo lỗi
-> không cài đặt được module HRM và services trên cùng 1 máy tính

```
cài đặt HRM hiển thị tên là service
![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/96155021/762a20e8-6743-4206-beda-55e5031ac0b0)

Lỗi Khi cài Service vào máy đã cài HRM
![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/96155021/955904f2-a58a-4578-8f31-2f1bf0190bb3)

**Comment by ongtrieuhau** [comment]
Cập nhập [3.23.0704.1](https://github.com/dh-hos/dhg.hospitalhrm/commit/b111937d2350f611f01d73a936a75812b5253bf0)

**Comment by le-an-87** [comment]
Hiện tại còn lỗi chưa cài được 2 module HRM và service chung 1 máy tính nhe anh!
*** với anh coi thêm lỗi này giùm em nhe**
Chấm thêm giờ các chức năng THÊM, CHỈNH, XÓA, IN, ĐÓNG không chạy được.
Data test: dbphuoclong_062023
![image](https://github.com/dh-hos/dhg.hospitalhrm/assets/96155021/7a21d6f1-84ce-4caf-bead-e5e46d948bcf)

**Comment by le-an-87** [comment]
Đã fix lỗi cài đặt module!
